### PR TITLE
Cleaning up of ImageSensor for use in future experiments 

### PR DESCRIPTION
**Pull request by jaredweiss**
Updated the ImageSensor to be able to take in lists and dicts as parameters by requiring them to be json serialized. Also updated unit tests.

### CODE REVIEW

**Comment by jaredweiss** [comment]
@scottpurdy Please review

**Comment by breznak** [comment]
@jaredweiss seems like you are successfully running unit-tests here. How do you tackle https://github.com/numenta/nupic.vision/issues/8 ?

**Comment by scottpurdy** [comment]
The clean ups are great. It looks like you are also changing the semantics of some places to JSON blobs. Can we pull those changes into a separate PR?

**Comment by jaredweiss** [comment]
@scottpurdy I'm considering that a part of the cleanup. The code can't fully be run otherwise.

**Comment by scottpurdy** [comment]
It is a functional change though so has implications for calling code. Anything like that needs to be more thoroughly looked at and it makes it harder when there are a bunch of purely stylistic changes mixed in.

**Comment by scottpurdy** [comment]
Should you be using YAML instead of JSON? I believe YAML decoding works with JSON but it is actually implemented as YAML so we should use that for the encoding as well, right?

**Comment by jaredweiss** [comment]
@scottpurdy It actually doesn't matter whether we use YAML or JSON. The string is decoded within python, not in the C++ code so we can define whichever encoding we want. When the yaml parser in C++ receives the parameter, it simply treats it as a string and python handles the decoding. So long as the spec we define and our implementation in the python match up, we're all good.

**Comment by scottpurdy** [comment]
I still think it should be YAML. That is what nupic.core supports so better to keep consistency in NuPIC. And it has the added benefits of supporting comments, etc. We still need to switch to JSON for web stuff though.

**Comment by jaredweiss** [comment]
@scottpurdy Please take a look at this. Separated the different aspects of this PR into multiple commits

**Comment by scottpurdy** [comment]
:+1:

**Pull request merged**
