### PR TITLE
Initial GUI and network for saccade experiment. Currently only trains SP

### LINKED ISSUE #24: Get ImageSensor network running with saccades and GUI
See parent #21 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/24041527-get-imagesensor-network-running-with-saccades-and-gui?utm_campaign=plugin&utm_content=tracker%2F3344350&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F3344350&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jaredweiss**
Fixes #24 and #22 

@scottpurdy Please review

### CODE REVIEW

**Comment by scottpurdy** [comment]
Can we do the ImageSensor and RandomSaccade explorer as one PR and the initial experiment/GUI as a follow on?

Also, in the future we may want to use the saccade direction as part of our TM prediction so would the image sensor output need to be the current saccade instead of the previous one?

**Comment by jaredweiss** [comment]
Would the "current" saccade be the one that just happened or that one that is about to happen (when explorer.next is run again)? Since the saccade has already happened (and the current output is the result of that saccade) I called the parameter prevSaccade but I think it's what you're referring to as the current saccade. Does it make more sense as currentSaccade? If you think so I'll rename it.

**Comment by scottpurdy** [comment]
Yes, I think your name is accurate. I was more wondering if that is what we will need in the future. I suppose this is fine for now.

Can you move the two experiment files to a separate PR?

**Comment by jaredweiss** [comment]
Could you elaborate more on what else we may need in the future?

**Comment by scottpurdy** [comment]
@jaredweiss - A lot of things :) but outside scope of this PR I think

**Comment by jaredweiss** [comment]
Ok. Closing this PR since it'll be replaced by separate PRs fixing #22 and #24

**Pull request closed without merging**
