### PR TITLE
fix vision_testbench.py example

### PR DESCRIPTION
**Pull request by myxo**
Fix vision_testbench.py. Where were some syntax errors.

### CODE REVIEW

**Comment by vankhoakmt** [comment]
it has no mistake, please try it again

**Comment by myxo** [comment]
Sorry, but I dont understand you. It's clear syntax error (switched lines and unimported library)

**Comment by breznak** [comment]
Thanks @myxo ! 
Sorry for the fuss, probably some mistake, your fix is clearly correct. 
@rhyolight ok to merge?

**Comment by rhyolight** [comment]
Sorry, I did not see this.

**Pull request merged**
