### PR TITLE
Cleaned up ImageSensor code

### PR DESCRIPTION
**Pull request by jaredweiss**
All style cleanup

@scottpurdy Please review when you get a chance

### CODE REVIEW

**Comment by scottpurdy** [comment]
On this line: https://github.com/jaredweiss/nupic.vision/blob/3446bc06aeb0f3f3d3d6524071499e354519eac4/nupicvision/regions/ImageSensor.py#L128

Rather than escaping quotes in a YAML string, you could set the default to `yaml.dump(["Default"])` or whatever.

**Comment by scottpurdy** [comment]
Keep in mind 3 blank lines before top level functions/classes and 2 before class methods

**Comment by scottpurdy** [comment]
Is this still needed with Python 2.7? https://github.com/jaredweiss/nupic.vision/blob/3446bc06aeb0f3f3d3d6524071499e354519eac4/nupicvision/regions/ImageSensor.py#L415

**Comment by scottpurdy** [comment]
Why is there an `_init` rather than just putting it in the `__init__`? It doesn't look like it is called anywhere else so might as well move contents of `_init` to the `__init__`.

**Comment by scottpurdy** [comment]
Done reviewing

**Comment by jaredweiss** [comment]
ping @scottpurdy

**Comment by scottpurdy** [comment]
Great work! :+1:

**Pull request merged**
